apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertsnitch-deployment
  namespace: prometheus-blackbox
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alertsnitch-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":9567,"dnsName":"alertsnitch-deployment","hostPort":0,"kind":"ClusterIP","name":"http","protocol":"TCP"}]]'
      labels:
        app: alertsnitch-deployment
    spec:
      containers:
      - image: registry.gitlab.com/yakshaving.art/alertsnitch:0.2
        envFrom:
        - secretRef:
            name: alertsnitch-secret
            optional: false
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9567
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        name: alertsnitch
        ports:
        - containerPort: 9567
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9567
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2
          timeoutSeconds: 2
        resources:
          requests:
            memory: 300Mi
            cpu: 10m
          limits:
            memory: 1Gi
            cpu: 500m
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
