apiVersion: v1
kind: Secret
metadata:
  name: alertsnitch-secret
  namespace: prometheus-blackbox
data:
  ALERSTNITCH_BACKEND: "mysql"
  ALERTSNITCH_DSN: "${MYSQL_USER}:${MYSQL_PASSWORD}@/${RDS_HOST}"
