apiVersion: v1
kind: Secret
metadata:
  name: alertsnitch-secret
  namespace: prometheus-blackbox
data:
  ALERSTNITCH_BACKEND: "postgres"
  ALERTSNITCH_DSN: "sslmode=disable user=${PGUSER} password=${PGPASSWORD} host=${PGHOST} database=${PGDATABASE}"