apiVersion: v1
kind: Service
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"  
  labels:
  name: alertsnitch-svc
  namespace: prometheus-blackbox
spec:
  ports:
  - name: http
    port: 9567
    protocol: TCP
    targetPort: 9567
  selector:
    app: alertsnitch-deployment
  sessionAffinity: None
  type: ClusterIP
